# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ytpull',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/ytpull',
                'lib_path': 'ytpull'},
  'syms': {'ytpull.core': {'ytpull.core.foo': ('core.html#foo', 'ytpull/core.py')}}}
